### ISSUE TITLE
is it needed that /var/log is writable?

### ISSUE THREAD

**Issue by dvic** [honeycombio/honeycomb-kubernetes-agent#169]
I see in the example that the mounted host path `/var/log` has `readOnly: false`. Is this intentional?

**Comment by MikeGoldsmith** [comment]
Thanks for creating the issue @dvic.

I'll defer to @robbkidd and @puckpuck on whether we need that file to be writable.

**Comment by puckpuck** [comment]
The agent requires write permissions to record state from parsed logs. This allows you to reconfigure the agent with a restart and have it pick up from where it left off.
