### ISSUE TITLE
Docs fix for rolling out config updates

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/honeycomb-kubernetes-agent#182]
Originally raised by @pbiggar. I accidentally moved the issue to our internal docs repo which they could no longer see - sorry!

Re-creating this issue for visibility.

**Comment by mjingle** [comment]
@pbiggar Thank you for raising this issue. The Docs repo is currently private, which is why you can't find it, but our engineers will make sure any reported issue will get to the right location. 

Original issue text:
> I'm not sure the correct place to report this, as I can't find a repo for the docs.
>
> At https://docs.honeycomb.io/getting-data-in/integrations/kubernetes/configuration/#uploading-a-configuration-file-to-a-cluster, I think (I'm not 100% sure) the command to restart the pods should be (as of k8s 1.15):
>
>`kubectl rollout restart ds/honeycomb-agent`
>
> instead of
>
> `kubectl delete pod --selector k8s-app=honeycomb-agent`

**Comment by MikeGoldsmith** [comment]
We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
