### ISSUE TITLE
Scalability of fluentd <> apiserver lists operations.

### ISSUE THREAD

**Issue by timothysc** [honeycombio/honeycomb-kubernetes-agent#2]
Depending on what you are listing from the api-server from your fluentd plugin, you could run into scaling issues.  To circumvent some of these problems, folks have bolstered the kubelet api to get pod.spec details (here is an example from bootkubes checkpointer - https://github.com/kubernetes-incubator/bootkube/blob/master/cmd/checkpoint/main.go#L170).  So a privileged daemonset pod can talk with it's local kubelet to obtain the meta-data needed to enrich logs, in cases where the operations needed to gather enough meta-data becomes expensive on larger loaded clusters.  

Hope this helps.  

/cc @hausdorff

**Comment by puckpuck** [comment]
Closing this issue due to age
