### ISSUE TITLE
Failed to send event to Honeycomb

### ISSUE THREAD

**Issue by nicks** [honeycombio/honeycomb-kubernetes-agent#21]
My honeycomb-agent is failing to send logs to honeycomb. I don't know how to debug this further. Here is the error we're seeing in the logs of the daemonset pod

```
time="2018-09-12T20:38:35Z" level=error msg="Failed to send event to Honeycomb" error="json: cannot unmarshal object into Go value of type []libhoney.Response" responseBody= status=0
```

any advice?

**Comment by emfree** [comment]
Hi @nicks, excellent debugging, sorry you ran into this! It looks like this agent is using an older version of the `libhoney-go` dependency that produced the very cryptic message you're getting, instead of a sane error message. I'll put up a patch to fix this.

**Comment by nicks** [comment]
wow, that was quick, thanks Eben!
