### ISSUE TITLE
check for nils on optional stats

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-kubernetes-agent#216]
As a followup from #206, check for other optional stats (Memory, Network, FileSystem, ?) to ensure they are handled appropriately if nil

**Comment by MikeGoldsmith** [comment]
We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
