### ISSUE TITLE
Update Ubuntu image for Circle

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-kubernetes-agent#227]
https://circleci.com/blog/ubuntu-14-16-image-deprecation/

Received notice that a job uses an Ubuntu 16.04-based image.

**Comment by MikeGoldsmith** [comment]
We only used `cimg/go:1.17` & `cibuilds/github:0.13.0` images for this repo - did we get a notification for this one or was this issue to check?

**Comment by MikeGoldsmith** [comment]
Closing this as we don't seem to use a ubuntu 14.16 image in this CircleCI workflow.

cimg/go is based on ubuntu 20
cibuilds/github is based on alpine
