### ISSUE TITLE
Add config option to ignore filepaths

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-kubernetes-agent#239]
**Is your feature request related to a problem? Please describe.**
The agent currently looks at every file in the container `/var/log` directory to generate events. This is a problem when something (like log rotation) creates a copy of the log file with another extension (like `tmp`), because that results in the agent scanning all the same log lines again, and creating duplicate events. As a side effect, this scenario also manifests in what appears as huge event ingest latency in Honeycomb, because the agent is scanning log lines that happened hours prior.

**Describe the solution you'd like**
Allow users to configure ignored file paths, so they can ignore temp files, as well as compressed files, since those cannot be parsed and result in errors in the agent log.

**Describe alternatives you've considered**
We can just add a warning to the docs to be wary of log rotation, but we don't have a good workaround at this time short of disabling log rotation.

**Additional context**
[internal asana](https://app.asana.com/0/526085303034087/1201979509997282/f)

**Comment by filip-ivan** [comment]
Isn't this double processing of the logs also impacting the volume of events being processed (and accounted for) by the platform? So basically the budget that a customer has is being consumed twice as fast.

**Comment by filip-ivan** [comment]
Also, have a look at the implementation of the filebeat log collector: if you just exclude reading rotated files, you cannot guarantee that you won't miss an event.
Looks like filebeat tracks its position on per file basis using the inode number of the file which doesn't change when it is rotated and that ensures they don't miss anything.
