### ISSUE TITLE
GKE AutoPilot cluster: Error from server ([denied by autogke-no-write-mode-hostpath])

### ISSUE THREAD

**Issue by beejiujitsu** [honeycombio/honeycomb-kubernetes-agent#267]
When attempting to apply `quickstart.yaml`, or use the official Helm chart, to a GKE AutoPilot cluster, I receive the following error output:

```
kubectl apply -f quickstart.yaml
serviceaccount/honeycomb-serviceaccount unchanged
clusterrolebinding.rbac.authorization.k8s.io/honeycomb-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/honeycomb-serviceaccount unchanged
Warning: Autopilot increased resource requests for DaemonSet honeycomb/honeycomb-agent to meet requirements. See http://g.co/gke/autopilot-resources.
Error from server ([denied by autogke-no-write-mode-hostpath]): error when creating "quickstart.yaml": admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-no-write-mode-hostpath]":["hostPath volume varlog in container honeycomb-agent is accessed in write mode; disallowed in Autopilot. Requested by user: 'mark@enso.finance', groups: 'system:authenticated'.","hostPath volume varlibdockercontainers used in container honeycomb-agent uses path /var/lib/docker/containers which is not allowed in Autopilot. Allowed path prefixes for hostPath volumes are: [/var/log/]. Requested by user: 'mark@enso.finance', groups: 'system:authenticated'."]}
```

**Versions**

`image: honeycombio/honeycomb-kubernetes-agent:2.5.2`

**Steps to reproduce**

1. `kubectl apply -f quickstart.yaml`
2. Receive error

**Additional context**

```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.201", GitCommit:"2dca91e5224568a093c27d3589aa0a96fd3ddc9a", GitTreeState:"clean", BuildDate:"2022-05-11T18:39:02Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

**Comment by MikeGoldsmith** [comment]
Thanks for raising the issue @beejiujitsu - we'll look into the problem. On the surface, it looks like GKE Autopilot requires additional resources to be defined.

**Comment by beejiujitsu** [comment]
Thanks for your reply, @MikeGoldsmith.

I'm not sure there's any tooling that would help here; however, there are a number of limitations documented here: https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview

Directly relevant are the Host options restrictions: https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#host_options_restrictions 

> HostPort and hostNetwork are not permitted because node management is handled by GKE. Using [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volumes in write mode is prohibited, while using hostPath volumes in read mode is allowed only for /var/log/ path prefixes. Using [host namespaces](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces) in workloads is prohibited.

My wild stab in that dark is that a possible workaround would be to use the Cloud Logging API: https://cloud.google.com/logging/docs/reference/api-overview

To retrieve pod/container logs, but I have neither the time nor experience to do that.

This seems like the classic shared VPS vs dedicated server problem in the webhosting business.
