### ISSUE TITLE
Question about parser

### ISSUE THREAD

**Issue by Arvindh-Mojo** [honeycombio/honeycomb-kubernetes-agent#329]
I'm currently trying out few new observability tools as an alternate to our existing solution. I'm trying to setup the honeycomb k8s agent to collect application logs. (k8s=EKS). 

Trying to understand how `watchers` work. Currently my applications logs are `stdout` and wanna understand what kind of `parser` i should be using for the configuration. 

Technically the apps doesnt output logs in `json` format. is there something i can define to simply ship the stdout logs from app container to honeycomb.

Let me know.

**Comment by kentquirk** [comment]
Hi, @Arvindh-Mojo. "Watchers" monitor a specific directory subtree and capture logs from it.

Each log can have a parser, and the different parsers you'd use depend on the format of the logs. We have [parsers for several common formats](https://docs.honeycomb.io/getting-data-in/integrations/kubernetes/configuration/#parsers), and there is also a regex parser (which I've just noticed is not documented!).

Its configuration is a list of patterns, each of which uses named capturing groups to identify specific fields in log entries that you wish to capture. Until we document it better, the best option is to look at [the test code](https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/main/parsers/regex_test.go) for an example how it works.

Please follow up if you have more questions.

**Comment by TylerHelmuth** [comment]
Closing this issue.  Please ping if you think it needs reopened.
