### ISSUE TITLE
docs: regex parser isn't documented

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/honeycomb-kubernetes-agent#332]
The regex parser in the agent is not documented on the honeycomb site or anywhere else other than its test code. Let's fix that.

**Comment by MikeGoldsmith** [comment]
We are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
