### ISSUE TITLE
agent is restarting when pod is not found

### ISSUE THREAD

**Issue by enc** [honeycombio/honeycomb-kubernetes-agent#333]
https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/66864979093c63a6dc423f435633b553a77d4e40/metrics/metadata.go#L52

this error is not handled gracefully.
We checked one pod ids and it was a CI runner that was done with the job.

```
level=error msg="Metadata: Pod not found" podUid=2fd21870-xxxx-xxxx-xxxx-4eea5b905015
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa89ce9]
```

**Comment by puckpuck** [comment]
I see where this breaks. Either write code so the `PodMetadata.GetXXX()` functions return 0 or a blank string when the Pod is nil, or change the logic in the accumulator to check if the Pod metadata was found first.

https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/main/metrics/metadata.go#L102
