### ISSUE TITLE
Support wildcard namespaces in WatcherConfig

### ISSUE THREAD

**Issue by tredman** [honeycombio/honeycomb-kubernetes-agent#50]

**Comment by seh** [comment]
Note that this would require granting permission to the agent to watch pods at cluster scope. Many people probably do that already, but it's worth documenting that it does not mean, "Watch pods in all the namespaces in which you happen to have permission."

**Comment by puckpuck** [comment]
Checking to see if this is addressed now.

I just did a quick test, and by omitting the `namespace` property from watcher config, the agent was able to tail logs from all namespaces with a matching selector.

**Comment by puckpuck** [comment]
Closing this one. We support all namepsaces or a single namespace today. If wider support is needed we can open another issue.
