### ISSUE TITLE
Feature request: Helm charts

### ISSUE THREAD

**Issue by noamt** [honeycombio/honeycomb-kubernetes-agent#54]
Helm is growing in popularity and it would be nice if we could have charts for `honeycomb-kubernetes-agent` on https://hub.helm.sh

**Comment by puckpuck** [comment]
We now have a [helm repo](https://github.com/honeycombio/helm-charts) with a chart for this agent, and will soon be part of Helm hub [PR](https://github.com/helm/hub/pull/326)
