### ISSUE TITLE
heapster is deprecated; update to use metrics-server?

### ISSUE THREAD

**Issue by cee-dub** [honeycombio/honeycomb-kubernetes-agent#85]
I'm integrating Honeycomb into our infrastructure and noticed that the manifests (and the helm chart) install [heapster](https://github.com/kubernetes-retired/heapster) at [v1.5.1](https://github.com/honeycombio/kubernetes-manifests/blob/master/metrics/honeycomb-heapster.yaml#L64). According to [deprecation.md](https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md), no updates have been made since k8s 1.13 when it was removed. 

Based on the above, I'd expect Honeycomb to be migrating to non-EOL methods of exporting cluster data into the service. Confusingly, the [latest commit](https://github.com/honeycombio/kubernetes-manifests/commit/4ba3027333bab13a658ce221372e87a332179c56) to Honeycomb manifests updates them for use with K8s v1.18.

Are there any plans to update the agent to use maintained metrics exporters?

**Comment by puckpuck** [comment]
We do have plans to do something here, but nothing concrete yet.
