### ISSUE TITLE
pod log paths don't work on pre-1.6 clusters

### ISSUE THREAD

**Issue by emfree** [honeycombio/honeycomb-kubernetes-agent#9]
On Kubernetes version 1.6+, container logs are symlinked 
`/var/log/pods/<podUID>/<containerName>_N.log -> /var/lib/docker/containers/...`

On Kubernetes 1.5, container logs are symlinked
`/var/log/containers/<pod_name>_<pod_namespace>_<container_name>-<container_id>.log -> /var/lib/docker/containers/...`

We should be able to use that path template on 1.5 clusters, but likely need to be more careful about handling log rotation. We need to do that in any case to properly handle explicit path watchers (e.g., for audit logs).

See https://github.com/kubernetes/kubernetes/blob/release-1.5/docs/proposals/kubelet-cri-logging.md for more background.

Relatedly, we should run the e2e tests on multiple cluster versions (v1.5-1.7 is probably a reasonable start).

**Comment by tredman** [comment]
Covered by https://github.com/honeycombio/honeycomb-kubernetes-agent/pull/18
